# NOTE: Generated By HttpRunner v4.3.0
# FROM: testcases/getMarket.yml
from httprunner import HttpRunner, Config, Step, RunRequest


class TestCaseGetmarket(HttpRunner):

    config = Config("getMarket").base_url("${ENV(base_url)}").verify(False)

    teststeps = [
        Step(
            RunRequest("getMarket")
            .get("/api/otc/api/v1/getMarket/")
            .with_headers(**{"lang": "en"})
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseGetmarket().test_start()
