# NOTE: Generated By HttpRunner v4.3.0
# FROM: testcases/login.yml
from httprunner import HttpRunner, Config, Step, RunRequest


class TestCaseLogin(HttpRunner):

    config = Config("Login").base_url("${ENV(base_url)}").verify(False)

    teststeps = [
        Step(
            RunRequest("Login")
            .with_variables(**{"var1": "value1", "var2": "value2"})
            .post("/api/login/")
            .with_headers(**{"lang": "en"})
            .with_json(
                {
                    "password": "02ee0be1761db38a2ab3cb3adab0d4886def79f00fab7ff2c4ec115c26cd3b71",
                    "captchaId": False,
                    "captchaNumber": None,
                    "deviceFingerprint": "_vmhjlh1667276599542",
                    "loginName": "TimmyHong",
                    "keepLogin": False,
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseLogin().test_start()
